name: skill_assessment
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  reorderable_grid_view: ^2.2.2
  get: ^4.6.5
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/data.json
    - assets/images/
    - assets/icons/

  uses-material-design: true